name: controle_vendas_e_estoque
description: "App para gestão de estoque eficiente"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #Suporte Off-line
  hive: ^2.2.3

  # Gerenciamento de estado
  provider: ^6.1.2

  # Integração com Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1

  # Formulários e validações
  #flutter_form_builder: ^8.1.1

  # Gráficos para relatórios
  #fl_chart: ^0.54.0

  # Gerar IDs únicos
  uuid: ^4.5.1

  # Formatação de números e datas
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

